# http://docs.haskellstack.org/en/stable/yaml_configuration/

# resolver by ghc version:
#
#   8.4.3:  nightly-2018-06-07
#   8.2.2:  lts-11.9
resolver: lts-11.9

packages:
- '.'

extra-deps: []

flags: {}

extra-package-dbs: []
