# -----------------------------------------------------------------------------
# $Id: Makefile,v 1.1.1.1 2002/12/09 21:51:47 ijones Exp $

TOP = ../..
include $(TOP)/mk/boilerplate.mk

SUBDIRS = src  # ToDo: doc

include $(TOP)/mk/target.mk




