#-----------------------------------------------------------------------------
# $Id: Makefile,v 1.3 2000/07/11 09:29:36 simonmar Exp $

TOP=../..
include $(TOP)/mk/boilerplate.mk

SGML_DOC = happy

include $(TOP)/mk/target.mk
