#-----------------------------------------------------------------------------
# $Id: Makefile,v 1.2 1997/12/16 12:40:56 simonm Exp $

TOP=../..
include $(TOP)/mk/boilerplate.mk

include $(TOP)/mk/target.mk
