# -----------------------------------------------------------------------------
# $Id: Makefile,v 1.3 1999/06/10 08:50:49 simonmar Exp $

TOP = ../..
include $(TOP)/mk/boilerplate.mk

INSTALL_DATAS = \
	HappyTemplate \
	HappyTemplate-ghc \
	HappyTemplate-coerce \
	HappyTemplate-arrays

override datadir = $(libdir)/happy

include $(TOP)/mk/target.mk
