# -----------------------------------------------------------------------------
# $Id: Makefile,v 1.1 1997/10/07 15:02:07 simonm Exp $

TOP = ../..
include $(TOP)/mk/boilerplate.mk

INSTALL_DATAS = \
	HappyTemplate \
	HappyTemplate-ghc \
	HappyTemplate-arrays \
	HappyTemplate-1_2 \
	HappyTemplate-ghc-1_2 \
	HappyTemplate-arrays-1_2

override datadir = $(libdir)/happy

include $(TOP)/mk/target.mk
